columns:
  - trans_date_trans_time
  - cc_num
  - merchant
  - category
  - amt
  - gender
  - zip
  - lat
  - long
  - city_pop
  - unix_time
  - merch_lat
  - merch_long
  - is_fraud

dtypes:
  trans_date_trans_time: str
  cc_num: int
  merchant: str
  category: str
  amt: float
  gender: str
  zip: int
  lat: float
  long: float
  city_pop: int
  unix_time: int
  merch_lat: float
  merch_long: float
  is_fraud: int

non_nullable:
  - trans_date_trans_time
  - cc_num
  - amt
  - zip
  - unix_time
  - is_fraud
